// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtVh1tecpNIppF5qzCm-z-jRgzk1KYDJk',
    appId: '1:312983175067:web:63eb8b5a3d2774649c2b3e',
    messagingSenderId: '312983175067',
    projectId: 'murderparty-83b6c',
    authDomain: 'murderparty-83b6c.firebaseapp.com',
    storageBucket: 'murderparty-83b6c.appspot.com',
    measurementId: 'G-PP1YY02QRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOQ3Y907HBxu6Awxq6OlwGoqmk-BsQq8k',
    appId: '1:312983175067:android:0ddf45bba660762c9c2b3e',
    messagingSenderId: '312983175067',
    projectId: 'murderparty-83b6c',
    storageBucket: 'murderparty-83b6c.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtVh1tecpNIppF5qzCm-z-jRgzk1KYDJk',
    appId: '1:312983175067:web:e2083a512b39c4969c2b3e',
    messagingSenderId: '312983175067',
    projectId: 'murderparty-83b6c',
    authDomain: 'murderparty-83b6c.firebaseapp.com',
    storageBucket: 'murderparty-83b6c.appspot.com',
    measurementId: 'G-762MRW2PYV',
  );

}